"""创建所有表

Revision ID: 2c76becab18f
Revises: 
Create Date: 2018-07-12 17:29:12.685935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c76becab18f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wish', 'isbn',
               existing_type=mysql.VARCHAR(length=13),
               nullable=False)
    op.alter_column('wish', 'uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wish', 'uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('wish', 'isbn',
               existing_type=mysql.VARCHAR(length=13),
               nullable=True)
    # ### end Alembic commands ###
