"""empty message

Revision ID: 835711a97644
Revises: 2c76becab18f
Create Date: 2018-07-22 08:47:50.017399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '835711a97644'
down_revision = '2c76becab18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wx_name', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('wx_open_id', sa.String(length=50), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user', 'wx_open_id')
    op.drop_column('user', 'wx_name')
    # ### end Alembic commands ###
